version: "2.4"

services:
  s3init:
    image: minio/mc
    volumes:
      - ./etc/policy.json:/opt/policy.json
      - ./etc/s3init.sh:/opt/s3init.sh
    entrypoint: ["/opt/s3init.sh"]
    networks:
      - s3
    depends_on:
      - s3
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - MINIO_SH_USER
      - MINIO_SH_PASSWORD
