version: '2'

services:
  httpd:
    build: .
    volumes:
      - "./apache2:/etc/apache2"
      - "./server:/var/www/html"
    ports:
      - "80:80"
    tty: true
  redis:
    restart: unless-stopped
    image: redis:7.0.4-alpine
    expose:
      - "6379"
    volumes:
      - "./data:/data"
