version: '2'

services:
  lighttpd:
    image: sebp/lighttpd
    volumes:
#      - "./data:/data"
      - "./lighttpd:/etc/lighttpd"
      - "./build:/var/www/localhost/cgi-bin"
    ports:
      - "80:80"
    tty: true
  redis:
    restart: unless-stopped
    image: redis:7.0.4-alpine
    expose:
      - "6379"
    volumes:
      - "./data:/data"
