version: '2.2'

services:
  ambulance:
    build: service
    cpus: 2
    pids_limit: 8192
    mem_limit: 1G
    memswap_limit: 1G
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - "users:/var/ambulance/users"
      - "diseases:/var/ambulance/diseases"
    ports:
      - "17171:31337"

  cleaner:
    build: cleaner
    cpus: 1
    pids_limit: 256
    mem_limit: 256M
    memswap_limit: 256M
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - "users:/tmp/users"
      - "diseases:/tmp/diseases"
    depends_on:
      - ambulance

volumes:
  users:
  diseases:
