version: '2.1'

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - "59999:9100"

  nginx-log-exporter:
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter
    command: ["-config-file", "/config/prometheus-nginxlog-exporter.yaml"]
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./config:/config/
    restart: unless-stopped
    ports:
      - "59998:4040"
