version: "3.9"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./DATA/logs/nginx:/var/log/nginx
    depends_on:
      - php
  php:
    build:
      args:
        user: php
        uid: 1000
      context: ./
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    env_file: .env
  mysql:
    image: mysql
    volumes:
      - ./DATA/logs/mysql:/var/log/mysql
      - ./DATA/mysql:/var/lib/mysql
      - ./DATA/mysql-files:/var/lib/mysql-files
      - ./DATA/mysql-data:/docker-entrypoint-initdb.d
    env_file: .env
    restart: unless-stopped