version: '3'
services:
  linkextractor:
    container_name: linkextractor
    restart: unless-stopped
    build: .
    ports:
      - 80:8080
    volumes:
      - ./db:/home/app/db
      - ./secret:/home/app/secret
