name: Check KV service
jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: apt-get update
    - name: Install docker
      run: |
          apt-get install docker.io
          apt-get install docker-compose
    - name: Install checker reqirements
      run: |
          apt-get install python3-pip
          cd checkers/kv
          pip3 install -r requirements.txt
    - name: Build and run service
      run: |
          cd services/kv
          docker-compose build
          docker-compose up
    - name: Check service
      run: |
          cd checkers/kv
          ./check_check.sh 100
