name: Reset current game

on:
  workflow_dispatch:
    inputs:
      approve:
        description: "Are you sure you want to reset the game? ALL DATA WILL BE DELETED!"
        type: boolean
        required: true

jobs:
  reset-game:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Save private key
        run: 'echo "$SSH_KEY" > ~/cloud_ssh_private_key; chmod 600 ~/cloud_ssh_private_key'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.CLOUD_SSH_PRIVATE_KEY }}
      - name: Reset game
        if: ${{ inputs.approve }}
        run: |-
          ansible-playbook --private-key=~/cloud_ssh_private_key -D -v ../checksystem/ansible/cs-stop.yml;
          ansible-playbook --private-key=~/cloud_ssh_private_key -D -v -t update ../checksystem/ansible/cs-deploy.yml
          ansible-playbook --private-key=~/cloud_ssh_private_key -D -v ../checksystem/ansible/cs-init.yml;
          ansible-playbook --private-key=~/cloud_ssh_private_key -D -v ../checksystem/ansible/cs-start.yml;
        working-directory: "${{ github.workspace }}/ansible"
