name: Update checkers

on:
  workflow_dispatch:
    inputs:
      approve:
        description: "Are you sure to update checkers?"
        type: boolean
        required: true

jobs:
  update-checkers:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Save private key
        run: 'echo "$SSH_KEY" > ~/cloud_ssh_private_key; chmod 600 ~/cloud_ssh_private_key'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.CLOUD_SSH_PRIVATE_KEY }}
      - name: Update and restart checkers
        if: ${{ inputs.approve }}
        run: |-
          ansible-playbook --private-key=~/cloud_ssh_private_key -D -v checkers.yml
        working-directory: "${{ github.workspace }}/ansible"
